### ISSUE TITLE
About code and proposed dataset

### ISSUE THREAD

**Issue by MontaEllis** [lhyfst/SphereHead#1]
Nice work! When will you opensource code and dataset, or annotations?

**Comment by lhyfst** [comment]
Thank you for your interest! We will make the related resources publicly available once the paper is accepted by any conference or journal.

**Comment by andypinxinliu** [comment]
hi, congrats on the acceptance. Will you release the dataset and the code?

**Comment by FeiiYin** [comment]
hi, congrats on the acceptance. Will you release the code?
